version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rezervacnysystem_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - rezervacny-net

  web:
    image: nginx:stable-alpine
    container_name: rezervacnysystem_web
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rezervacny-net

  db:
    image: mysql:8.0
    container_name: rezervacnysystem_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rezervacnysystem
      MYSQL_USER: rezervacny
      MYSQL_PASSWORD: rezervacny
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rezervacny-net

networks:
  rezervacny-net:

volumes:
  db_data:

